name: Build and push backend changes to Docker Hub

on:
  push:
    paths:
      - 'ServerSprintEyeGit/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add perm to gradlew
        run: chmod +x ./ServerSprintEyeGit/gradlew

      - name: Enable containerd image store
        run: |
          sudo mkdir -p /etc/docker
          echo '{ "features": { "containerd-snapshotter": true } }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build backend jar
        run: ./gradlew clean build -x test
        working-directory: ./ServerSprintEyeGit

      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./ServerSprintEyeGit
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/sprinteye_backend:latest
            ${{ vars.DOCKERHUB_USERNAME }}/sprinteye_backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/sprinteye_backend:cache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/sprinteye_backend:cache,mode=max